### PR TITLE
Clearing screen & mac fix

### PR DESCRIPTION
**Pull request by joshmartine**
First of all, I'm not sure why the 3 commits from Oct 6 are there. pls help.

Anyway, `getRenderer()->clear();` is now called when the core engine updates.
This didn't do anything for me so I was googling around and stumbled upon [this](https://stackoverflow.com/questions/51992402/sdl-pollevent-prevents-render-unless-window-moved-or-resized) which basically says nothing will render until the window is resized. I looked into using the metal driver for sdl2 but the only examples I could find were in objective-c so we have a homemade fix. The main idea is that the window is resized to 1279x720 and then back to 1280x720 shortly after.

### CODE REVIEW

**Comment by ianw3214** [comment]
I think the clear colour is never set in the Engine, which may be a source of error.  
If that doesn't work, I would try the [the bottom answer of this stackoverflow post](https://stackoverflow.com/questions/34967628/sdl2-window-turns-black-on-resize).  

I'll also ask other Mac users if they experience the same issue, if none of the solutions above work and everyone else experiences the same issues, I'll merge the pull request.

**Comment by joshmartine** [comment]
Even with the clear colour: 
fixed

I'll look at the link and get back in a bit.

**Comment by joshmartine** [comment]
Unfortunately, it seems the problem in the link is a different problem. This problem is that nothing is rendering until the screen is resized while their problem is that no events are registered while resizing. This is technically a problem but I believe they would be different.

**Comment by ianw3214** [comment]
Yeah I thought it would maybe be worth a try since it's a related issue, none of the other Mac users are experiencing the same issue so I'm not sure what the problem is.

**Comment by darren-moore** [comment]
Does opengl 3.2 work?
try `SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 2);`

**Comment by joshmartine** [comment]
No, I still get a black screen if I don't include the "fix" even though the screen is being cleared and the clear color is not black.

**Pull request merged**
