### PR TITLE
Set window attributes before creating window.

### PR DESCRIPTION
**Pull request by joshmartine**
This is necessary to get a proper OpenGL context on a mac. I don't think it has any impact on other operating systems.

### CODE REVIEW

**Comment by darren-moore** [comment]
This change isn't compatible with Windows. Could probably use the preprocessor for an easy fix.

**Comment by darren-moore** [comment]
@joshmartine what is the error with the initial code on Mac?

**Comment by joshmartine** [comment]
@darren-moore without the change, I'm getting this when I run the game:


```
Shader compilation failed:
ERROR: 0:1: '' :  version '330' is not supported
ERROR: 0:1: '' : syntax error: #version
ERROR: 0:2: 'layout' : syntax error: syntax error

Shader compilation failed:
ERROR: 0:1: '' :  version '330' is not supported
ERROR: 0:1: '' : syntax error: #version

Shader compilation failed:
ERROR: 0:1: '' :  version '330' is not supported
ERROR: 0:1: '' : syntax error: #version
ERROR: 0:2: 'layout' : syntax error: syntax error

Shader compilation failed:
ERROR: 0:1: '' :  version '330' is not supported
ERROR: 0:1: '' : syntax error: #version
```

However, could we test it by only moving the line that has `SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);` above window creation and keep the rest below? That seems to work for me. but I'm not exactly sure how to go about that on github, I'm a bit of a noob.

**Comment by darren-moore** [comment]
Try the original, but change the opengl version:
```
	// Setup openGL attributes
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 2);
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
	SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8);
	SDL_GL_SetSwapInterval(1);

**Comment by darren-moore** [comment]
I think I see what's going on. By setting these properties only after opengl context creation, SDL doesn't know what version to use so it defaults to one that will work with your system. In your case, the default is  < Opengl 3.3, but the shaders use opengl 3.3, hence the shader compilation errors.

These `SetAttribute` properties should indeed be set before context creation as your pull request(PR) is. Now, the reason your PR didn't work for me is because my GPU doesn't support opengl 4.6.

Now, I'm also a GitHub noob, but if it works anything like GitLab, just make a new commit and it will show up here!

Finally, I think `	SDL_GL_SetSwapInterval(1);` should be set after context creation. So after Ian confirms below, change it to 3.3, move that line down, commit, and we should be good to merge in (if it works...)

@ianw3214 check this out. Can we move to opengl 3.3?

**Pull request merged**
